{"uuid":"477cdbde-c0fe-4e56-ab13-184f2c749060","name":"An uncaught error was detected outside of a test","historyId":"ec9bbc4b9b53d6d50b40009a15355674:d41d8cd98f00b204e9800998ecf8427e","status":"broken","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > c3a6aaabe7ba5da001b83d1c3303c16fbc2dc241647c760005eee5d5aa7c313c is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"ReferenceError: The following error originated from your test code, not from Cypress.\n\n  > c3a6aaabe7ba5da001b83d1c3303c16fbc2dc241647c760005eee5d5aa7c313c is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at Suite.eval (webpack://cypress2/./cypress/e2e/API testing/httpreq.cy.js:2:22)\n    at Kt (webpack://cypress2/./node_modules/allure-cypress/dist/cjs/index.js:1:16050)\n    at eval (webpack://cypress2/./node_modules/allure-cypress/dist/cjs/index.js:1:16165)\n    at eval (webpack://cypress2/./cypress/e2e/API testing/httpreq.cy.js:1:0)\n    at eval (http://localhost:54491/__cypress/tests?p=cypress\\e2e\\API%20testing\\httpreq.cy.js:34:12)\n    at eval (<anonymous>)\nFrom previous event:\n    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:54491/__cypress/runner/cypress_runner.js:3486:19)\n    at Promise._then (http://localhost:54491/__cypress/runner/cypress_runner.js:1239:17)\n    at Promise.then (http://localhost:54491/__cypress/runner/cypress_runner.js:1132:17)\n    at runScriptsFromUrls (http://localhost:54491/__cypress/runner/cypress_runner.js:111657:136)\n    at Object.runScripts (http://localhost:54491/__cypress/runner/cypress_runner.js:111698:12)\n    at $Cypress.onSpecWindow (http://localhost:54491/__cypress/runner/cypress_runner.js:41308:67)"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"cypress"},{"name":"host","value":"ASCINLAP60907"},{"name":"thread","value":"pid-20624-worker-main"},{"name":"package","value":"cypress.e2e.API testing.httpreq.cy.js"}],"links":[],"start":1731560628230,"fullName":"cypress/e2e/API testing/httpreq.cy.js#An uncaught error was detected outside of a test","testCaseId":"ec9bbc4b9b53d6d50b40009a15355674","stop":1731560628283}